version: '2'
services:
    fullstackdev_2017b-app:
        image: fullstackdev_2017b
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mariadb://fullstackdev_2017b-mariadb:3306/fullstackdev_2017b
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    fullstackdev_2017b-mariadb:
        extends:
            file: mariadb.yml
            service: fullstackdev_2017b-mariadb
