version: '2'
services:
    fullstackdev_2017b-mariadb:
        image: mariadb:10.1.17
        # volumes:
        #     - ~/volumes/jhipster/fullstackdev_2017B/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=fullstackdev_2017b
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
